Updated user documentation
zamzterz/Flask-pyoidc pull request #121
Opened 2022-01-26 15:58 UTC by infohash

Addresses #120

2022-01-26 17:01 UTC, zamzterz requested changes
Really nice! 👏 

Most comments are minor, but there are some structural questions (on my part) and the mentioning of "keycloak" which should be replaced. 🙂

2022-01-26 17:01 UTC, zamzterz commented on docs/quickstart.md
> +[the name of the view function](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.route)), or if using Blueprints, you
💯

2022-01-27 17:15 UTC, infohash commented on docs/configuration.md
> +# As shown earlier, if you are using Static Client Configuration, then specify
They both are arguments of [provider metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).

2022-01-29 10:08 UTC, zamzterz commented
The failing tests were due to the removed `example/__init__.py` file - I've fixed it up.
Thanks 👏

2022-01-29 10:08 UTC, zamzterz approved these changes

2022-01-29 10:10 UTC, merged